### PR TITLE
Fix bugs in the commands

### LINKED ISSUE #291: Bugs in the deleteAppointment, delete and listAppointment Command

### PR DESCRIPTION
**Pull request by G13nd0n**
Closes #291

### CODE REVIEW

File: src/main/java/bookbob/Main.java [hunk 1]
```diff
@@ -245,6 +251,9 @@ public static void main(String[] args) throws IOException {
                 } catch (DateTimeException e) {
                     logger.log(Level.WARNING, "Error processing appointment command", e);
                     System.out.println("Error in adding appointment, wrong time format");
+                } catch (ArrayIndexOutOfBoundsException e) {
+                    logger.log(Level.WARNING, "Error processing appointment command", e);
+                    System.out.println("Error in adding appointment, missing nric, date and time.");
```
Comment (yentheng0110) [inline src/main/java/bookbob/Main.java:256]: There is a typo, this is for finding appointment

**Review by yentheng0110 — CHANGES_REQUESTED** [review]
Overall LGTM, minor changes required

**Review by yentheng0110 — APPROVED** [review]
