### PR TITLE
Fix bugs

### LINKED ISSUE #296: [PE-D][Tester D] Duplicate patient records allowed for add command
Steps to replicate:

add n/James Ho ic/S9534567A p/91234567 d/Asthma m/Albuterol ha/NUS-PGPR dob/01011995 v/21-10-2024 15:48al/Pollen s/Female mh/Diabetes

add n/James Ho ic/S9534567A p/91234567 d/Asthma m/Albuterol ha/NUS-PGPR dob/01011995 v/21-10-2024 15:48al/Pollen s/Female mh/Diabetes

These records might not make sense fuctionality wise as they have identical fields down to the date and time of visit.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: lucas-sc0/ped#1

### LINKED ISSUE #298: [PE-D][Tester D] Able to bypass mandatory field enforcement for add command
User can bypass mandatory field enforcement of name and nric by concatenating the identifier or just by adding white space.

Steps to replicate:
add n/ic/v/04-11-2024 09:00

or 

add n/ ic/ v/04-11-2024 09:00

Can be abused to add blank records with only date and time of visit.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: lucas-sc0/ped#3

### LINKED ISSUE #300: [PE-D][Tester B] List Appointments Command
When `list appointments` or even `list Appointments` is used, a list of users is provided. The commands with the space cause the processing of the `list command` when the user may be trying to use the `listAppointments` command. The reference output is below:

Although the input does deviate from the format specified in the UG, it is good to reject commands that are inputted with improper formatting. Thanks!

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: DarkDragoon2002/ped#2

### LINKED ISSUE #302: [PE-D][Tester D] Duplicate users records (NRIC) exists causes non deterministic delete function
If duplicate users (NRIC) records exist , will only choose one to delete in seemingly no specific order. Can’t choose which one to delete.

Steps to replicate:

add n/Patricia Chan ic/S9890897U v/04-11-2024 09:00

add n/Patricia Chan ic/S9890897U v/04-11-2025 09:00

add n/Patricia Chan ic/S9890897U v/21-12-2025 09:00

delete S9890897U

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: lucas-sc0/ped#6

### LINKED ISSUE #303: [PE-D][Tester E] Able to input same person with same details multiple times.
I am able to put in the same details of the same person multiple times, could create redundancies in the list 

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: shaunngoh/ped#1

### LINKED ISSUE #304: [PE-D][Tester D] Duplicate user records (NRIC) causes non deterministic edit function
If duplicate users (NRIC) records exist , will only choose one to edit in seemingly no specific order. Can’t choose which one to edit.

Steps to replicate:

add n/Patricia Chan ic/S9890897U v/04-11-2024 09:00

add n/Patricia Chan ic/S9890897U v/04-11-2025 09:00

add n/Patricia Chan ic/S9890897U v/21-12-2025 09:00

edit ic/S9890897U /to s/Female

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: lucas-sc0/ped#7

### LINKED ISSUE #309: [PE-D][Tester C] Add patient command allows adding duplicate patients with the exact same information.
Steps to reproduce:
- Enter `add n/James Ho ic/S9534567A p/91234567 d/Asthma m/Albuterol ha/NUS-PGPR dob/01011990 v/21-10-2024 15:48 al/Pollen s/Female mh/Diabetes` multiple times
- Each command will succeed
- Enter `list`
- The duplicate patients are all displayed

This could potentially inconvenience the user, as he may accidentally add the same patient again unknowingly, and this will affect further delete or edit commands.

Perhaps checking could be implemented to prevent duplicate patients from being added.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jinzihan2002/ped#1

### LINKED ISSUE #311: [PE-D][Tester A] Duplicate IC provided when adding new patient.
Able to add a new patient (Charizard Blastoise) with the same IC number as a previous patient (Ben Chua). Would it be better if you checked against existing IC numbers before adding a new patient since some of your features also depend on the IC number of a patient and given that IC numbers have the feature of being unique for every individual. A duplicate IC number in the case of a typo might mean that a new visit is not registered under the correct intended patient (Charizard Blastoise) as seen in the second screenshot. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: ChuaCleon/ped#1

### LINKED ISSUE #321: [PE-D][Tester B] Allows Saving of Illegal IC numbers
The program allows me to save ICs with illegal formats. It's a minor bug but it would be good to check if the inputted IC numbers are actually valid assuming the users are to actually use ICs which is important when accessing health record data etc. Would be good to do a check on user input and ask them to retry. Thanks!

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: DarkDragoon2002/ped#4

### LINKED ISSUE #324: [PE-D][Tester B] Multiple Patients with the same IC number allowed
The program allows the user to input multiple patients with different names with the same IC number which can be quite dangerous and confusing especially in a clinic administration setting. Allowing for duplicate users will cause confusion in administration. Luckily, it is easy to fix with a quick check.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: DarkDragoon2002/ped#5

### PR DESCRIPTION
**Pull request by G13nd0n**
Closes #296 
Closes #298 
Closes #300 
Closes #302 
Closes #303 
Closes #304 
Closes #309 
Closes #311 
Closes #321 
Closes #324

### CODE REVIEW

File: src/main/java/bookbob/parser/Parser.java [hunk 1]
```diff
@@ -60,6 +65,11 @@ public static void handleCommand(String input, CommandHandler commandHandler, Re
             break;
 
         case "list":
+            if (inputArray.length > 1) {
```
Comment (yentheng0110) [inline src/main/java/bookbob/parser/Parser.java:68]: Nice catch!

**Review by yentheng0110 — COMMENTED** [review]
LGTM!
